version: '3'
services:
  stock-market-charting-mysql:
    image: mysql:8.0.18
    ports:
      - "33085:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker-build-db:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d
  
  eureka-service:
    image: eureka-app
    build: mid-Tier/eureka-discovery-server
    ports:
      - 8761:8761
      
  authentication-service:
    image: authentication-app
    build: mid-Tier/authentication-service
    ports:
      - 8082:8082
    depends_on:
      - stock-market-charting-mysql
      - eureka-service
    links:
      - stock-market-charting-mysql
      - eureka-service
      
  company-service:
    image: company-app
    build: mid-Tier/company-service
    ports:
      - 8085:8085
    depends_on:
      - stock-market-charting-mysql
      - eureka-service
    links:
      - stock-market-charting-mysql
      - eureka-service
  
  excel-upload-service:
    image: excel-upload-app
    build: mid-Tier/excel-upload
    ports:
      - 8084:8084
    depends_on:
      - stock-market-charting-mysql
      - eureka-service
      - zuul-service
    links:
      - stock-market-charting-mysql
      - eureka-service
      
 
  zuul-service:
    image: zuul-app
    build: mid-Tier/zuul-gateway
    ports:
      - 8083:8083
    depends_on:
      - company-service
      - authentication-service
      - excel-upload-service
    links:
      - company-service
      - authentication-service
      - excel-upload-service
      
  angular-service:
    image: angular-app
    build: front-end/stock-market/dist
    ports:
      - 4200:80
    depends_on:
      - company-service
      - authentication-service
      - eureka-service
      - zuul-service
      - excel-upload-service
    links:
      - company-service
      - authentication-service
      - eureka-service
      - zuul-service
      - excel-upload-service
        
  
   